org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

kotlin.code.style=official
kotlin.native.cacheKind=none

android.useAndroidX=true
android.nonTransitiveRClass=true

# For iOS framework
kotlin.native.binary.memoryModel=strict

# If using CMP resources later
org.jetbrains.compose.experimental.uikit.enabled=true